# Generated by Django 2.2.3 on 2019-08-08 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catastro', '0001_initial'),
        ('recaudacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecaudacionDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('numero', models.IntegerField(verbose_name='Catastro')),
                ('lectura_anterior', models.PositiveIntegerField(verbose_name='Lectura anterior')),
                ('lectura_actual', models.PositiveIntegerField(verbose_name='Lectura actual')),
                ('consumo', models.PositiveIntegerField(verbose_name='Consumo M3')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Tarifa base')),
                ('base_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Tarifa base reserva')),
                ('valor_consumo_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor consumo máximo')),
                ('valor_excedente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor por excedente')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.LecturaDetalle', verbose_name='Lectura')),
                ('recaudacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recaudacion.Recaudacion', verbose_name='Recaudación')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Recaudaciones Detalle',
            },
        ),
    ]
