# Generated by Django 2.2.3 on 2019-08-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaudacion', '0003_auto_20190810_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='recaudacion',
            name='total_administracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Administración'),
        ),
        migrations.AddField(
            model_name='recaudacion',
            name='total_alcantarillado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alcantarillado'),
        ),
        migrations.AddField(
            model_name='recaudacion',
            name='total_derecho_conexion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total derecho conexion'),
        ),
        migrations.AddField(
            model_name='recaudaciondetalle',
            name='administracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Administración'),
        ),
        migrations.AddField(
            model_name='recaudaciondetalle',
            name='alcantarillado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alcantarillado'),
        ),
        migrations.AddField(
            model_name='recaudaciondetalle',
            name='derecho_conexion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Derecho conexión'),
        ),
    ]
