# Generated by Django 2.2.3 on 2019-08-07 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('identificacion', models.CharField(max_length=13, unique=True, verbose_name='Identificación')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Página Web')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimieno')),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='HOM', max_length=50, verbose_name='Sexo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='parametro/abonado/', verbose_name='Retrato')),
            ],
            options={
                'verbose_name': 'Abonado',
                'verbose_name_plural': 'Abonados',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('periodo', models.DateField(unique=True, verbose_name='Período consumo')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('consumo_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Consumo M3')),
                ('total_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa base')),
                ('total_base_reserva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa base reserva')),
                ('total_excedente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total excedente')),
                ('total_consumo_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total consumo máximo')),
                ('total_general', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total general')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoLectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tipo de lectura',
                'verbose_name_plural': 'Tipos de lectruas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número medidor')),
                ('descripcion', models.CharField(max_length=254, verbose_name='Descripcion')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('lectura_inicial', models.IntegerField(default=0, verbose_name='lectura inicial')),
                ('asignar', models.BooleanField(default=False, verbose_name='Asignar')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Medidores',
            },
        ),
        migrations.CreateModel(
            name='Catastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('numero', models.IntegerField(unique=True, verbose_name='Numero catastral')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de Ingreso')),
                ('descripcion', models.CharField(blank=True, max_length=254, null=True, verbose_name='descripcion')),
                ('suspender', models.BooleanField(default=False, verbose_name='Suspender')),
                ('abonado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.Abonado', verbose_name='Abonado')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametro.Descuento', verbose_name='Descuento')),
                ('medidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catastro.Medidor', verbose_name='Medidor')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametro.Pago', verbose_name='Forma de pago')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametro.Servicio', verbose_name='Servicio')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Planilla catastral',
                'verbose_name_plural': 'Planillas Catastrales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('descripcion', models.CharField(max_length=254, verbose_name='Descripcion')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
            },
        ),
        migrations.AddField(
            model_name='abonado',
            name='barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.Barrio', verbose_name='Barrio / Sector'),
        ),
        migrations.AddField(
            model_name='abonado',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='LecturaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('lectura_anterior', models.PositiveIntegerField(verbose_name='Lectura anterior')),
                ('lectura_actual', models.PositiveIntegerField(verbose_name='Lectura actual')),
                ('consumo', models.PositiveIntegerField(verbose_name='Consumo M3')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Tarifa base')),
                ('base_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Tarifa base reserva')),
                ('valor_consumo_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor consumo máximo')),
                ('valor_excedente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor por excedente')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('catastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.Catastro', verbose_name='Clave catastral')),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.Lectura', verbose_name='Lectura')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametro.Tarifa', verbose_name='Tarifa')),
                ('tipo_lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.TipoLectura', verbose_name='Tipo de lectura')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Detalle Lecturas',
                'unique_together': {('lectura', 'catastro')},
            },
        ),
    ]
