# Generated by Django 2.2.3 on 2019-08-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catastro',
            name='alcantarillado',
            field=models.BooleanField(default=True, verbose_name='Alcantarillado'),
        ),
        migrations.AddField(
            model_name='catastro',
            name='derecho_conexion',
            field=models.BooleanField(default=True, verbose_name='Derecho conexión'),
        ),
        migrations.AddField(
            model_name='catastro',
            name='peticionario',
            field=models.CharField(choices=[('Nuevo abonado', 'Nuevo abonado'), ('Nuevo en la comunidad', 'Nuevo en la comunidad')], default='NUEVO', max_length=50, verbose_name='Peticionario'),
        ),
    ]
