# Generated by Django 2.2.3 on 2019-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='modelo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Modelo'),
        ),
    ]
