# Generated by Django 2.2.3 on 2019-08-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0002_auto_20190831_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastro',
            name='alcantarillado',
            field=models.BooleanField(default=True, verbose_name='Paga alcantarillado'),
        ),
        migrations.AlterField(
            model_name='catastro',
            name='derecho_conexion',
            field=models.BooleanField(default=True, verbose_name='Paga conexión'),
        ),
        migrations.AlterField(
            model_name='catastro',
            name='peticionario',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Antiguo', 'Antiguo'), ('Nuevo en la comunidad', 'Nuevo en la comunidad')], default='NUEVO', max_length=50, verbose_name='Peticionario'),
        ),
        migrations.AlterField(
            model_name='catastro',
            name='suspender',
            field=models.BooleanField(default=False, verbose_name='Suspendido'),
        ),
    ]
