# Generated by Django 2.2.3 on 2019-08-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0003_auto_20190831_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonado',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=50, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='catastro',
            name='peticionario',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Antiguo', 'Antiguo'), ('Nuevo en la comunidad', 'Nuevo en la comunidad')], default='Antiguo', max_length=50, verbose_name='Peticionario'),
        ),
    ]
