# Generated by Django 2.2.3 on 2019-08-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0008_auto_20190831_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonado',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=50, verbose_name='Sexo'),
        ),
    ]
