# Generated by Django 2.2.3 on 2019-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0010_auto_20190831_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='total_derecho_conexion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total derecho conexion'),
        ),
    ]
