# Generated by Django 2.2.3 on 2019-08-31 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0002_auto_20190831_1011'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catastro', '0011_lectura_total_derecho_conexion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.LecturaDetalle', verbose_name='Lectura')),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametro.Multa', verbose_name='Multa')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Detalle de multas',
                'unique_together': {('lectura', 'multa')},
            },
        ),
    ]
