# Generated by Django 2.2.3 on 2019-09-11 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
                ('rango_inicial', models.IntegerField(default=0, verbose_name='Rango Inicial')),
                ('rango_superior', models.IntegerField(default=0, verbose_name='Rango Superior')),
                ('valor_excedente', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor por excedente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('base', models.DecimalField(decimal_places=2, default=2.25, max_digits=4, verbose_name='Tarifa base')),
                ('base_reserva', models.DecimalField(decimal_places=2, default=0.55, max_digits=4, verbose_name='Tarifa base reserva')),
                ('base_consumo', models.IntegerField(default=11, verbose_name='Base consumo M3')),
                ('consumo_maximo', models.IntegerField(default=30, verbose_name='Consumo máximo')),
                ('valor_consumo_maximo', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Valor consumo máximo')),
                ('administracion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Gastos administrativos')),
                ('alcantarillado', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alcantarillado')),
                ('derecho_conexion', models.DecimalField(decimal_places=2, default=400, max_digits=5, verbose_name='Derecho conexion')),
                ('derecho_conexion_nuevo_comunidad', models.DecimalField(decimal_places=2, default=800, max_digits=5, verbose_name='Derecho conexion nuevo comunidad')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tipo servicio',
                'verbose_name_plural': 'Tipo servicios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Forma pago')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Forma de pagos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Multas y otros valores',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('descripcion', models.CharField(max_length=150, unique=True, verbose_name='Nombre Comercial')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parametro/', verbose_name='Logotipo')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario modifica')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descuento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['id'],
            },
        ),
    ]
