# Generated by Django 2.2.3 on 2019-08-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='administracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Gastos administrativos'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='alcantarillado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alcantarillado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='derecho_conexion',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=5, verbose_name='Derecho conexion'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='derecho_conexion_nuevo_comunidad',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=5, verbose_name='Derecho conexion nuevo comunidad'),
        ),
    ]
